name: flutter_kin_cake_kun_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.2 #ใช้ฟอนต์ Google Fonts
  font_awesome_flutter: ^10.12.0 # ใช้ไอคอนจาก Font Awesome
  url_launcher: ^6.3.2 # ใช้เปิดเว็บ เปิดแอปโทรศัพท์ 
  flutter_map : ^8.2.2 # ใช้แสดงแผนที่
  latlong2: ^0.9.1 # ใช้จัดการพิกัดลพติจูดและละติจูด
  carousel_slider: ^5.1.2 #ใช้สร้างสไลด์โชว์

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  icons_launcher: ^3.0.3 # ใช้สร้างไอคอนแอปสำหรับ Android และ iOS

icons_launcher:
  image_path: "assets/icon/icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/